# Generated by Django 4.2.7 on 2023-11-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('version', models.CharField(blank=True, max_length=5, verbose_name='버전')),
                ('file_path', models.FileField(blank=True, upload_to='', verbose_name='파일')),
                ('is_use', models.BooleanField(null=True, verbose_name='사용여부')),
                ('create_date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '프로그램 정보',
                'verbose_name_plural': '프로그램 목록',
                'db_table': 'program_info',
            },
        ),
    ]
