# Generated by Django 4.2.7 on 2023-12-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('published_date_time', models.DateField(verbose_name='발행일')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='뉴스코드')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.providerinfo', verbose_name='언론사 아이디')),
            ],
            options={
                'verbose_name': '뉴스 정보',
                'verbose_name_plural': '뉴스 목록',
                'db_table': 'news_info',
            },
        ),
        migrations.CreateModel(
            name='RawArticleInfo',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='기사코드')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('provider', models.CharField(max_length=20, verbose_name='언론사명')),
                ('category', models.CharField(max_length=20, verbose_name='뉴스 통합분류체계')),
                ('byline', models.CharField(max_length=10, verbose_name='기자 이름')),
                ('provider_news_id', models.CharField(max_length=200, verbose_name='언론사 뉴스ID')),
                ('publisher_code', models.CharField(max_length=200, verbose_name='언론사 뉴스 코드')),
                ('provider_link_page', models.CharField(blank=True, max_length=200, verbose_name='언론사 원본 링크페이지')),
                ('printing_page', models.CharField(max_length=200, verbose_name='지면번호 이름')),
                ('published_at', models.DateField(verbose_name='발행일')),
                ('enveloped_at', models.DateField(verbose_name='수집일시')),
                ('dateline', models.DateField(verbose_name='출고시간')),
            ],
            options={
                'verbose_name': '원본기사 정보',
                'verbose_name_plural': '원본기사 목록',
                'db_table': 'raw_article_info',
            },
        ),
        migrations.CreateModel(
            name='RawArticleImageInfo',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('title', models.CharField(max_length=200, verbose_name='주소')),
                ('raw_article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.rawarticleinfo', verbose_name='기사아이디')),
            ],
            options={
                'verbose_name': '기사 이미지 정보',
                'verbose_name_plural': '기사 이미지 목록',
                'db_table': 'raw_article_image_info',
            },
        ),
        migrations.CreateModel(
            name='PagerInfo',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('page', models.CharField(max_length=5, verbose_name='페이지명')),
                ('pager_image', models.ImageField(upload_to='news/paper', verbose_name='지면 이미지')),
                ('order', models.IntegerField(verbose_name='순서')),
                ('code', models.CharField(db_index=True, max_length=25, verbose_name='지면코드')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.newsinfo', verbose_name='뉴스 아이디')),
            ],
            options={
                'verbose_name': '지면 정보',
                'verbose_name_plural': '지면 목록',
                'db_table': 'paper_info',
            },
        ),
        migrations.CreateModel(
            name='IncidentInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('name', models.CharField(max_length=20, verbose_name='분류체계')),
                ('code', models.CharField(max_length=20, verbose_name='코드값')),
                ('raw_article', models.ManyToManyField(blank=True, to='news.rawarticleinfo', verbose_name='뉴스아이디')),
            ],
            options={
                'verbose_name': '사건사고 정보',
                'verbose_name_plural': '사건사고 목록',
                'db_table': 'incident_info',
            },
        ),
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('raw_article', models.ManyToManyField(blank=True, to='news.rawarticleinfo', verbose_name='고유번호')),
            ],
            options={
                'verbose_name': '카테고리 정보',
                'verbose_name_plural': '카테고리 목록',
                'db_table': 'category_info',
            },
        ),
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('paper_image', models.ImageField(upload_to='news/article', verbose_name='기사 이미지')),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='기사코드')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.pagerinfo', verbose_name='지면 아이디')),
                ('raw_article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.rawarticleinfo', verbose_name='원본기사 아이디')),
            ],
            options={
                'verbose_name': '기사 정보',
                'verbose_name_plural': '기사 목록',
                'db_table': 'article_info',
            },
        ),
    ]
