# Generated by Django 4.2.7 on 2023-12-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawarticleimageinfo',
            old_name='title',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='rawarticleinfo',
            name='dateline',
            field=models.DateTimeField(verbose_name='출고시간'),
        ),
        migrations.AlterField(
            model_name='rawarticleinfo',
            name='enveloped_at',
            field=models.DateTimeField(verbose_name='수집일시'),
        ),
        migrations.AlterField(
            model_name='rawarticleinfo',
            name='published_at',
            field=models.DateTimeField(verbose_name='발행일'),
        ),
    ]
