# Generated by Django 4.2.7 on 2024-01-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_title_rawarticleimageinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawarticleinfo',
            name='byline',
            field=models.CharField(max_length=20, verbose_name='기자 이름'),
        ),
    ]
