# Generated by Django 4.2.7 on 2024-01-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_rawarticleinfo_byline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawarticleinfo',
            name='byline',
            field=models.CharField(max_length=50, verbose_name='기자 이름'),
        ),
    ]
