# Generated by Django 4.2.7 on 2023-12-14 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('name', models.CharField(max_length=20, verbose_name='업체 이름')),
                ('memo', models.CharField(blank=True, max_length=50, verbose_name='업체 메모')),
                ('agent_name', models.CharField(blank=True, max_length=5, verbose_name='담당자 이름')),
                ('agent_phone', models.CharField(blank=True, max_length=15, verbose_name='담당자 연락처')),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='보고자 아이디')),
            ],
            options={
                'verbose_name': '업체',
                'verbose_name_plural': '업체 목록',
                'db_table': 'client_info',
            },
        ),
        migrations.CreateModel(
            name='ContractInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('agency_fee', models.IntegerField(verbose_name='대행 수수료')),
                ('paid_yn', models.BooleanField(verbose_name='결제 여부')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('started_date_time', models.DateField(default=django.utils.timezone.now, verbose_name='계약 시작일')),
                ('expired_date_time', models.DateField(verbose_name='계약 만료일')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.clientinfo', verbose_name='업체')),
                ('provider_no', models.ManyToManyField(blank=True, to='provider.providerinfo', verbose_name='계약 및 언론사 정보')),
            ],
            options={
                'verbose_name': '계약',
                'verbose_name_plural': '계약 목록',
                'db_table': 'contract_info',
            },
        ),
    ]
