# Generated by Django 4.2.7 on 2023-12-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCategoryInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('name', models.CharField(max_length=20, verbose_name='카테코리명')),
            ],
            options={
                'verbose_name': '언론사 카테고리',
                'verbose_name_plural': '언론사 카테고리 목록',
                'db_table': 'provider_category_info',
            },
        ),
        migrations.CreateModel(
            name='ProviderInfo',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False, verbose_name='고유번호')),
                ('name', models.CharField(max_length=20, verbose_name='언론사명')),
                ('copyright_fee', models.IntegerField(default=0, verbose_name='저작권료')),
                ('code', models.CharField(max_length=10, verbose_name='언론사코드')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.providercategoryinfo', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '언론사',
                'verbose_name_plural': '언론사 목록',
                'db_table': 'provider_info',
            },
        ),
    ]
